### ISSUE TITLE
New Player Guide Book

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#130]
Write a new player guide book that's given to players on module entry. This guide book should cover:

1.) Survival aspects - searching, healing, infection, hunger, badges
2.) Magic - Buying abilities, equipping abilities, mana, casting spells
3.) Items - Reloading guns, durability
4.) Ranged Combat - Distance from target, firepower, and all things related to the calculations.
5.) Progression - Gaining XP, gaining SP, purchasing stat upgrades
6.) Structures - Creating construction sites, claiming territory, building structures
7.) Gathering - Chopping wood, mining for ore
8.) Crafting - Finding blueprints, learning blueprints, using crafting devices
9.) Any other topics not covered in the other sections.

**Comment by Drakaden** [comment]
Topic: Survival Aspects
Sub Topic: Searching
Searching for loot is a vital part of the server in order to survive on the long run, you will find various items to help you progress, may it be food to keep yourself from dieing of hunger, ammo and weapons, and crafting components.
---
Sub Topic: Healing
Healing comes in 2 basic forms, natural healing and medical aid. Natural healing can be made faster with the Natural Regeneration skill by raising it. Natural healing can also be sped up by staying in an outpost.
---
Sub Topic: Infection
Sometimes the zombies blows will infect your character, and if you are really unlucky, sometimes the infection will keep growing for a while. Infection will slowly goes down on it's own in time. Some medical aids can also help healing infection. If you reach 100% infection, you are dead.
---
Sub Topic: Hunger
Food is a commonly important part of the survival of the game, you will need to keep your character fed in order to stay alive, the hunger measure is represented in a bar in the Rest Menu (pressing R or using the omnitool)
---
Sub Topic: Badges
Badges are exploration tokens, you will find them by searching around the world of the server, each badge can only be taken once per character, but gives decent experience and give bits of lore to read.

**Comment by Drakaden** [comment]
Topic: Magic
Sub Topic: Buying/Finding Ability
You can buy basic abilities from NPC merchants at outpost for gold currency. You can also find some in searching spots and some can be crafted with blueprints.
Sub Topic: Equipping Abilities
Equipping Abilities, also named AMP, can be done at outposts where AMP terminals are installed, from here, just follow the instructions on the terminal.
Sub Topic: Mana
Mana is necessary to cast any spells, a character starts at 0 mana, and so need invested right away for any spell usage by allocating points into Mana, in the Rest Menu (Pressing R or using the omnitool). Mana recover over time and some mana kits can be crafted to restore it, staying at an outpost make it recover faster.
Sub Topic: Casting Spells
Spells aren't an innate feat you can use right away, like abilities, they need equipped at an AMP terminal (See "Equipping Abilities" to know how). Each spell has their own mana cost, cooldown and time to cast. Equipped gear can also affect the speed of casting spells.

**Comment by Drakaden** [comment]
Topic: Items
Sub Topic: Reloading/Unloading guns
Reloading a gun is not done automatically, the player must use the omnitool Reload ability in order to reload. You may only reload a gun that you have currently equipped. Unloading a gun can be done by dragging the magazine in the arrow slot back into the inventory bag. It is suggested to quick slot the reload ability of the omnitool so you do not end up wasting time looking for it every times.

---

Sub Topic: Durability
Items crafted always start at maximum durability, items found in searching spots varies in durability. A piece of gear that reaches 0 durability cannot be used anymore unless repaired, but can still be sold to NPCs for gold currency. The durability value also affect the performance of guns, a lower durability means lesser damage output.

**Comment by Drakaden** [comment]
Topic: Ranged Combat
Sub Topic: Distance from target
Each guns types have a specific distance that they need respected in order to do maximum damage and/or accuracy: A handgun is best shot mid-range, a repeater (SMG) mid-range as well, a shotgun is best shot very close while a rifle/sniper must shoot from far away.

---

Sub Topic: Firepower
Firepower is an indication of how much damage your gun can do.
**This subtopic need expanded once firepower is modified to have a better understanding of it**

---

Sub Topic: Stopping Power
**Need a proper description of what it does, i'm not sure if it does anything right now.**

**Comment by Drakaden** [comment]
Topic: Progression
Sub Topic: Gaining XP
In order to evolve your character, you will need to obtain XP (Experience), this can be done by questing, killing zombies and participating to events. Each time you hawve enough XP to reach a level, you will obtain SPs (Skill Points).

----

Sub Topic: SP (Skill Point)
Skill points are obtained by leveling up, each allocation use a certain amount of SP and increase every times more are invested into them.

Sub Topic: Purchasing Stats Upgrades
In order to use SPs, you need to allocate them in stats upgrades, this can be done by pressing R or using the omnitool to open the Rest Menu. Each stat has a different cost and the SP requirements rise every times a new rank is purchased.

**Comment by Drakaden** [comment]
Topic: Structures
Sub Topic: Creating Construction Sites
In order for a player to build anything, they first need to build a territory marker, this can be done by using the omnitool ability related to structures. Once a territory marker is set, the player can build various things inside of it. A territory marker cannot overlap another territory's marker radius.

---

Sub Topic: Territory Claiming
Territory Claiming is done by building a territory marker, each type of territory marker has a radius limit and a number of placeables that can be built inside of them. More than one territory can be claimed, but none can be overlapped. A territory claim can be shared permissions by using the marker.

---

Sub Topic: Building Structures
Structures can only be built inside a claimed territory marker, each structures can be placed, moved, rotated and previewed before building it. Once built, you can still move and rotate them. Each structure cost a certain amount of materials to build, in order to build, you need the materials in your bag (You don't need to carry everything in same time, in fact some structures would make it impossible to do) and a hammer (Light hammer being the usual choice), light hammers can be either crafted or found in search sites.

**Comment by Drakaden** [comment]
Topic: Gathering
Sub Topic:: Chopping Wood
In order to collect wood material, a player must attack a tree placeable with any sharp weapons (No bludgeons). Every hit to the tree is a chance to receive wood, and each hit also decrease the durability of your weapons. You can decrease the durability loss by equipping an AMP specific for it and the chances of getting wood can be improved the same way if you find and equip the appropriate AMP. Each node can be depleted and disappear, the node will take some time before respawning with materials ready to be harvested again.

---

Sub Topic: Mining Ore
In order to collect ore material, a player must attack an ore vein placeable with any sharp weapons (No bludgeons). Every hit to the vein is a chance to receive an ore, and each hit also decrease the durability of your weapons. You can decrease the durability loss by equipping an AMP specific for it and the chances of getting ore can be improved the same way if you find and equip the appropriate AMP. Each node can be depleted and disappear, the node will take some time before respawning with materials ready to be harvested again.

**Comment by Drakaden** [comment]
Topic: Crafting
Sub Topic: Blueprints
Blueprints are used to make anything crafting related, once a blueprint is used, the blueprint is consumed. Once a blueprint is learned, it does not need to be learned again. The first blueprints the player will find are by being purchased from the outpost NPC for gold currency. Anything further than NPC blueprints need researched at a Research Terminal, which can be built in a territory claim. Researching blueprints demand that the player invest into the stats "Research" and each research cost time and gold currency.

---

Sub Topic: Crafting Devices
In order to craft anything, a player must use a crafting station specific to the craft expertise the target item is focused into (Example, Melee weapons uses Smithy Station), crafting devices can be freely used anywhere they are. A player can make crafting devices in a Territory Claim.

**Comment by zunath** [comment]
This is a good start. I need someone else to proofread it and fix the grammar/spelling issues before we put it into the game.
