### ISSUE TITLE
Apply repeated search penalty for search site campers

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#159]
Players are currently able to park characters at search sites and periodically loot them when the search cooldown timer resets.

Some potential fixes for this:

1.) Lock search cooldowns by CD key
2.) Increase the DC based on the number of consecutive searches within the same area.
3.) Check login/logout history of the character to apply penalties.

Option 2 is my preferred method but I'd like to hear some other opinions.

**Comment by Drakaden** [comment]
Personally i was only doing it because i thought i was free to do so, if it is becoming a rule i won't abuse it.

As for alternatives, how about changing the loot table quality if repeated too many times? And will come back to normal after some time is spent not looting it?

**Comment by Drakaden** [comment]
Though i assume that will only be a problem until the new search system is implemented.

**Comment by SexyKat** [comment]
I believe CDkey lock is preferred, as increasing the DC based on consecutive searches in the same area would be detrimental for the module in that players would feel that if someone has been in an area they wanted to loot recently, they will get nothing out of it and log off. It'll also prevent people from partying/interacting/exploring together since the second person is getting nothing (or at least diminished returns) for their trouble/time.

**Comment by zunath** [comment]
@Drakaden : Although you were what brought the issue up, it's not specifically directed at you. It's a potential area for exploitation that other players might take advantage of, so I thought it warranted discussion.

@SexyKat : Just to be clear - the DC penalties would only apply to the character that's logging on and off every few hours. It wouldn't impact other players (search DCs, timers, etc. are all character-based)

**Comment by Drakaden** [comment]
I personally don't have an issue with the search camping as you are forced behind a timed lock either ways, and there isn't enough players playing/doing it to warrant a huge attention about it right now, but that,s just my own opinion on the matter.

**Comment by NariKat** [comment]
The problem is not camping sites with one character, but doing it with several, hence multiplying the profit unlimitedly at absolutely no risk, especially when players find the sweet search sites and just camp-long on them with an army of alts to funnel all those resources onto the main character - and even if they didn't, I don't think this is how the module is meant to be played. It doesn't create any interaction or opportunity for neither players or DMs that someone has 3+ alts camping somewhere logging on to loot and then logging off instantly.

**Comment by zunath** [comment]
I'm having trouble justifying the extra work this will entail. Normally I'd automate a restriction to prevent something like this but in this situation I think we'll just enforce it as a rule on the DM side. If it becomes a bigger problem then we'll revisit but for now we've got bigger fish to fry.
