### ISSUE TITLE
Barbarian Speed Ability Disc

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#177]
Player recommends Barbarian Speed be implemented. It grants a 20% movement speed increase if you're wearing light or medium armor. 

I think this would be a perfect fit so long as we put a cooldown and maybe a mana cost on it. Open for discussion!

**Comment by NariKat** [comment]
Barbarian speed is 10% speed increase if I am correct. I don't see an issue with making an amp with it, rather than a perk. The thing to keep in mind is that it works as long as you wear medium or light armour (or clothes) as you said, but with CZS's current system, every armour is clothes, so wearing heavy armour wouldn't prevent from taking benefit of it. Which might not be a bad thing either, just pointing it out.

**Comment by taelon875** [comment]
Why don't we do a modified Expeditious Retreat spell? It could give a movement speed increase, and make it castable on others. Great spell for an Enhancement mage, Obviously the duration would be increased by wisdom and enhancement.
