### ISSUE TITLE
Enemies not granting XP when killed from afar with long distance firearms

### ISSUE THREAD

**Issue by NariKat** [zunath/CyberpunkZombieSurvival_JVM#182]
Sometimes zombies are not granting XP when being killed with long-range firearms, presumably due to the distance to the target. This happens even when getting kills from the firearm's optimal ranges, and it's common that you will oneshot a zombie with 25-30 damage and still get no XP credit from the kill. 

I suggest increasing XP range globally to account for this, at least while the character is wielding long-range firearms.

**Comment by taelon875** [comment]
I think we should just increase xp range to global anyway, it really is not that much of an issue. IF players are found abusing this while staying in a safe spot while someone else kills for them across the map it would just be considered exploiting. Because with DoT spells i am force to stick around them instead of running off and I wouldn't get credit (even if that worked).

**Comment by taelon875** [comment]
BEGIN TRANSACTION

UPDATE dbo.ServerConfiguration
SET MaxExpGainDistance = 100
WHERE ServerConfigurationID = 1

-- rollback
-- commit

SELECT *
FROM dbo.ServerConfiguration

**Comment by zunath** [comment]
Ran this on prod. See if there's a change.
