### ISSUE TITLE
New Spells: Holy and Enhancement (possible adds to Evocation)

### ISSUE THREAD

**Issue by taelon875** [zunath/CyberpunkZombieSurvival_JVM#187]
Holy Spell:
Holy Shot
Deals Damage is Casted Upon Hostile. Damage could be calculated from Holy and maybe have bonus from evocation skill.

Heals Damage if cased upon friendly targets.

**Comment by zunath** [comment]
Closing this one and adding it to #205 

I'm not in favor of healing "friendly targets" because the definition of "friendly" may change. I.E: You'd have to make someone hostile first, then the functionality would change. I think that's confusing to players. Can discuss more over in the other ticket if you disagree.
