### ISSUE TITLE
Adjust DC / Lock Timers on search sites

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#80]
Player reports it would be more fun if the respawn time on search sites was lowered and the DC increased. In other words, more difficult to find things but able to do it more often.

Look into possibly removing the lock altogether and instead base the DC on a timer itself. I.E: starts at 10, increases with each search and slowly decreases over time. If this is done, we need to look at all search related skills and abilities to see how they wold need to be changed. In addition, need to look into ways to prevent search site camping.

**Comment by Drakaden** [comment]
Player would be unable to calculate correctly when they can search again before the DC is lowered, making it hard to seize if it is a good time to search or not, should use a different approach.

**Comment by zunath** [comment]
Min/Maxing is not something I'm typically accommodating for.

**Comment by Drakaden** [comment]
How about... we can keep trying to scavenge, the DC will raise as you would think the idea is, the DC would eventually be unable to be beaten because you cannot succeed on a 20 search DC, and once it reach that stage the Dc cannot raise anymore?
it would be a ssimple as calculating the search of the player +20 + 1 to know when the DC stop raising(edited)
then you,d have to know how long the Dc's decay is and by how much
This system will make looting take longer though and would ignite irritation into players from overly clicking for each search

---

Search idea (Nereida helped me flesh it out):
Base Search DC is say 5.
Each Search attemp searches for 1 item, and increases DC by say 2.
A Character has a decay on the search timer that is 1 DC decrease per hour.  THis can be increased by +1 for every 5 points of search. (It would be possible to get a total of +4 decay per hour)
This allows for multiple searches, and the difficulty scales up. But those that use the one spot too much get a huge DC and they have to wait a while for it to drop.
So lower characters could hit the spot once or twice and have a DC of 9. That is reasonible, they wait two hours to come back and their DC is now 7, they search and it is now back to 9.

---

My thought would be that while you search and you have the AMP on, the decay would register it at the time you had it equipped, that would affect the decay over time and you'd have no timer lock and you'd be able to equip or unequip it freely
this way it has all the desired effects
I think with that setup and with what has been suggested by Collin and Nereida, this new seasrch system could work

**Comment by taelon875** [comment]
I was thinking the Decay should register when it triggers every hour. So you have to actively wear the decay AMP. That way you can't just abuse wearing it when you go searching.

**Comment by Drakaden** [comment]
The goal of this is to not force people to have to wear this AMP at all time.

**Comment by zunath** [comment]
We lowered the DC on the search sites a few weeks ago. I think I'm going to leave the lock timers as-is for now. There's too much work involved to change things and it works well enough as it is.
